name: CD - Acceptance & Deploy (Test Env) + Rollback

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build_test:
    name: Build + Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build con Maven
        run: mvn -B clean package --file pom.xml

      - name: Ejecutar tests unitarios/integración
        run: mvn -B test --file pom.xml

      - name: Subir artefacto (jar)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar


  deploy_test_env:
    name: Deploy to Test Env (Docker) + Acceptance + Rollback
    needs: build_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Descargar artefacto (jar)
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Build imagen GREEN (nueva versión)
        run: docker build -t app:green .

      - name: Levantar GREEN en ambiente de prueba
        run: |
          docker run -d --name green -p 8080:8080 app:green
          sleep 10

      - name: Acceptance tests (smoke)
        run: |
          echo "Chequeando servicio..."
          curl -f http://localhost:8080/ || (echo "Acceptance FAIL" && exit 1)

      - name: Deploy OK si acceptance pasa
        run: echo "Deploy GREEN aceptado en ambiente de prueba."

      - name: Rollback automático si falla acceptance/deploy
        if: failure()
        run: |
          echo "Falló GREEN. Ejecutando rollback..."
          docker logs green || true
          docker stop green || true
          docker rm green || true
          echo "Rollback completado."

